export default [
  {
    id: 1,
    title: "Boneco",
    description: "teste teste teste teste teste teste teste teste teste teste",
    price: 100,
    image: require("../assets/boneco.png"),
  },
  {
    id: 2,
    title: "Robô",
    description: "teste teste teste teste teste teste teste teste teste teste",
    price: 1000,
    image: require("../assets/boneco2.png"),
  },
  {
    id: 3,
    title: "Caneca",
    description: "teste teste teste teste teste teste teste teste teste teste",
    price: 200,
    image: require("../assets/caneca.png"),
  },
  {
    id: 4,
    title: "Construção",
    description: "teste teste teste teste teste teste teste teste teste teste",
    price: 1000,
    image: require("../assets/construcao.png"),
  },
  
  {
    id: 5,
    title: "Dado",
    description: "teste teste teste teste teste teste teste teste teste teste",
    price: 100,
    image: require("../assets/dado.png"),
  },
  {
    id: 6,
    title: "Óculos",
    description: "teste teste teste teste teste teste teste teste teste teste",
    price: 500,
    image: require("../assets/oculos.png"),
  },
  {
    id: 7,
    title: "Pelucia",
    description: "teste teste teste teste teste teste teste teste teste teste",
    price: 300,
    image: require("../assets/pelucia.png"),
  },  
  {
    id: 8,
    title: "Pulseira",
    description: "teste teste teste teste teste teste teste teste teste teste",
    price: 100,
    image: require("../assets/pulseira.png"),
  },
  {
    id: 9,
    title: "Pulseira",
    description: "teste teste teste teste teste teste teste teste teste teste",
    price: 100,
    image: require("../assets/pulseira2.png"),
  },
];